# Generated by Django 4.2.6 on 2023-10-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=100)),
                ("mobile_number", models.IntegerField()),
                ("gst_number", models.IntegerField()),
                ("party_type", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email_id", models.EmailField(max_length=254)),
                ("landline_number", models.IntegerField()),
                ("contact_person", models.CharField(max_length=100)),
            ],
        ),
    ]
