# Generated by Django 4.2.6 on 2023-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("party_master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partymaster",
            name="gst_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="partymaster",
            name="landline_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="partymaster",
            name="mobile_number",
            field=models.CharField(max_length=10),
        ),
    ]
